channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - perl
  - pandoc=2.9.2.1
  - tornado=5.1.1
  - sphinx=2.4.4
  - pip:
    - numpy==1.19.1
    - notedown==1.5.1
    - nbformat==5.0.7
    - sphinx-gallery==0.7.0
    - recommonmark==0.6.0
    - nbconvert==5.6.1
    - nbsphinx==0.7.1
    - ipython
    - ipykernel==5.3.4
    - numba==0.51.1
    - llvmlite==0.34.0
    - https://github.com/szha/mx-theme/tarball/master
    - seaborn==0.10.1
    - jieba==0.42.1
    - scikit-learn==0.23.2
    - cython==0.29.21
    - pytype==2020.8.17
    - pytest==6.0.1
    - pytest-env==0.6.2
    - pytest-cov==2.10.1
    - pytest-xdist==2.1.0
    - pylint==2.6.0
    - pylint-quotes==0.2.1
    - flaky==3.7.0
    - flake8==3.8.3
    - mock==4.0.2
    - mxnet-cu101==1.6.0
    - scipy==1.5.2
    - regex==2020.7.14
    - nltk==3.5
    - sacremoses==0.0.43
    - spacy==2.3.2
    - sentencepiece==0.1.91
    - sphinx-autodoc-typehints==1.11.0
