channels:
  - conda-forge
dependencies:
  - python=3.5
  - pip
  - perl
  - pandoc=2.9.2.1
  - tornado=5.1.1
  - sphinx=2.4.4
  - pip:
    - numpy==1.18.4
    - notedown==1.5.1
    - sphinx-gallery==0.6.2
    - recommonmark==0.6.0
    - nbconvert==5.6.1
    - nbsphinx==0.6.1
    - ipython
    - ipykernel
    - numba==0.47
    - llvmlite==0.31.0
    - https://github.com/szha/mx-theme/tarball/master
    - seaborn
    - jieba
    - scikit-learn==0.21.3
    - cython
    - pytype==2020.5.7
    - pytest==5.2.3
    - pytest-env==0.6.2
    - pytest-cov==2.8.1
    - pytest-xdist==1.30.0
    - pylint==2.4.4
    - pylint-quotes==0.2.1
    - flaky==3.6.1
    - flake8==3.7.9
    - mock<3
    - mxnet-cu101==1.6.0
    - scipy==1.3.2
    - regex==2020.4.4
    - nltk==3.4.5
    - sacremoses==0.0.35
    - spacy==2.2.2
    - sentencepiece==0.1.83
    - sphinx-autodoc-typehints==1.7.0
